# Generated by Django 4.2.4 on 2023-09-06 12:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meal', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BodyInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('height', models.CharField(max_length=64, verbose_name='身高')),
                ('weight', models.CharField(max_length=64, verbose_name='体重')),
            ],
        ),
    ]
