# Generated by Django 4.2.4 on 2023-09-09 07:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('meal', '0002_bodyinfo'),
    ]

    operations = [
        migrations.DeleteModel(
            name='BodyInfo',
        ),
    ]
