# Generated by Django 4.2.4 on 2023-09-21 05:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('meal', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomMealPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField(verbose_name='Start Date')),
                ('end_date', models.DateField(verbose_name='End Date')),
                ('daily_plans', models.ManyToManyField(blank=True, related_name='custom_daily_plans', to='meal.dailymealplan')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='custom_meal_plans', to='meal.userinfo', verbose_name='User')),
            ],
        ),
        migrations.RemoveField(
            model_name='weeklymealplan',
            name='day1',
        ),
        migrations.RemoveField(
            model_name='weeklymealplan',
            name='day2',
        ),
        migrations.RemoveField(
            model_name='weeklymealplan',
            name='day3',
        ),
        migrations.RemoveField(
            model_name='weeklymealplan',
            name='day4',
        ),
        migrations.RemoveField(
            model_name='weeklymealplan',
            name='day5',
        ),
        migrations.RemoveField(
            model_name='weeklymealplan',
            name='day6',
        ),
        migrations.RemoveField(
            model_name='weeklymealplan',
            name='day7',
        ),
        migrations.RemoveField(
            model_name='weeklymealplan',
            name='user',
        ),
        migrations.DeleteModel(
            name='MonthlyMealPlan',
        ),
        migrations.DeleteModel(
            name='WeeklyMealPlan',
        ),
    ]
