# Generated by Django 4.2.4 on 2023-09-22 05:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('meal', '0004_alter_dailymealplan_breakfast_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipes',
            name='user',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='recipes', to='meal.userinfo', verbose_name='User'),
        ),
    ]
