# Generated by Django 4.2.4 on 2023-09-22 13:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('meal', '0006_userpreferences'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userpreferences',
            name='creation_date',
        ),
        migrations.CreateModel(
            name='last_ingredients',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_ingredients', models.CharField(blank=True, default='', max_length=512, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='last_ingredients', to='meal.userinfo')),
            ],
        ),
    ]
